ARG BASE_IMAGE=rust:1.72-bullseye
FROM ${BASE_IMAGE} AS builder
WORKDIR /app
COPY . /app
RUN rustup default stable
RUN git clone --depth 1 --branch 2020 https://github.com/RedDwarfTech/synctex.git
RUN cd synctex && gcc -c -fPIC *.c && gcc -shared *.o -o libsynctex_parser.so -lz
RUN cp synctex/libsynctex_parser.so ./src/so/
RUN RUSTFLAGS='-L ./src/so' cargo build --release

FROM debian:bullseye-slim
LABEL maintainer="jiangtingqiang@gmail.com"
WORKDIR /app
ENV ROCKET_ADDRESS=0.0.0.0
# generate the dump file when every time increase 16MB
ENV MALLOC_CONF="prof:true,lg_prof_interval:24"
COPY --from=builder /app/settings.toml /app
COPY --from=builder /app/log4rs.yaml /app
COPY --from=builder /app/target/release/texhub-server /app/
COPY --from=builder /app/src/so/libsynctex_parser.so /app/
COPY --from=builder /app/src/so/libsynctex_parser.so /usr/lib/
RUN apt-get update -y && apt-get install curl libpq5 -y
CMD ["./texhub-server"]