[texhub]
compile_base_dir = "/opt/data/project"
tpl_files_base_dir = "/opt/data/tpl-files"
# cv_api_url = "http://10.98.93.22:11015"
x_access_token = "demo"
render_api_url = "http://cv-render-service.reddwarf-pro.svc.cluster.local:8000"
y_websocket_api_url = "http://tex-websocket-service.reddwarf-pro.svc.cluster.local:3000"
compile_group_name = "g-comp-queue"
compile_stream_redis_key = "texhub-server:proj:s-comp-queue"
compile_status_cached_key = "texhub-server:proj:queue"
fileinfo_redis_key = "texhub-server:proj:file"
default_tex_document = "\\documentclass{article}\n\n\\begin{document}\nHello, World!\n\\end{document}"
proj_cache_key="texhub-server:proj:info"