apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: texhub-server-service-pv-claim
  namespace: reddwarf-pro
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: nfs-texhub-server-pv
  volumeMode: Filesystem
