// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::model::diesel::tex::tex_schema::*;
use serde::Deserialize;
use serde::Serialize;

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = tex_comp_queue)]
pub struct TexCompQueue {
    pub id: i64,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub comp_status: i32,
    pub project_id: String,
    pub version_no: String,
    pub comp_result: i32,
    pub complete_time: i64,
}

#[derive(Insertable, Queryable, QueryableByName, Debug, Serialize, Deserialize, Default, Clone)]
#[diesel(table_name = tex_project)]
pub struct TexProject {
    pub id: i64,
    pub proj_name: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub proj_status: i32,
    pub template_id: i64,
    pub project_id: String,
    pub nickname: String,
    pub archive_status: i32,
    pub deleted: i32,
}

#[derive(Insertable, Queryable, QueryableByName, Debug, Serialize, Deserialize, Default, Clone)]
#[diesel(table_name = tex_template)]
pub struct TexTemplate {
    pub id: i64,
    pub name: String,
    pub remark: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub template_status: i32,
    pub template_id: i64,
    pub preview_url: Option<String>,
    pub template_code: String,
    pub online_status: i32,
    pub source: Option<String>,
    pub font_size: Option<String>,
    pub main_color: Option<String>,
    pub theme: Option<String>,
    pub language: String,
    pub intro: String,
    pub template_type: i32,
    pub pdf_name: String,
    pub main_file_name: String,
}

#[derive(Insertable, Queryable, QueryableByName, Debug, Serialize, Deserialize, Default, Clone)]
#[diesel(table_name = tex_file)]
#[serde(default)]
pub struct TexFile {
    pub id: i64,
    pub name: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub doc_status: i32,
    pub project_id: String,
    pub file_type: i32,
    pub file_id: String,
    pub parent: String,
    pub main_flag: i16,
    pub sort: i32,
    pub yjs_initial: i16,
    pub file_path: String
}

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = tex_proj_editor)]
pub struct TexProjEditor {
    pub id: i64,
    pub role_id: i32,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub collar_status: i32,
    pub sort: i32,
    pub project_id: String,
    pub trash: i32,
    pub archive_status: i32,
    pub proj_status: i32,
}

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = tex_file_version)]
pub struct TexFileVersion {
    pub id: i64,
    pub name: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub project_id: String,
    pub file_id: String,
    pub content: String,
    pub action: i32,
    pub snapshot: String,
}

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = tex_proj_folder)]
pub struct TexProjFolder {
    pub id: i64,
    pub folder_name: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub sort: i32,
    pub proj_type: i32,
    pub default_folder: i32,
}

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = tex_proj_folder_map)]
pub struct TexProjFolderMap {
    pub id: i64,
    pub folder_id: i64,
    pub created_time: i64,
    pub updated_time: i64,
    pub project_id: String,
    pub user_id: i64,
    pub proj_type: i32,
}