// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::model::diesel::tex::tex_schema::*;
use serde::Deserialize;
use serde::Serialize;

#[derive(Insertable, Queryable, QueryableByName, Debug, Serialize, Deserialize, Default, Clone)]
#[diesel(table_name = tex_project)]
pub struct TexProject {
    pub id: i64,
    pub proj_name: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub proj_status: i32,
    pub template_id: i64,
    pub project_id: String,
    pub nickname: String,
}

#[derive(Insertable, Queryable, QueryableByName, Debug, Serialize, Deserialize, Default, Clone)]
#[diesel(table_name = tex_template)]
pub struct TexTemplate {
    pub id: i64,
    pub name: String,
    pub remark: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub template_status: i32,
    pub template_id: i64,
    pub preview_url: Option<String>,
    pub template_code: String,
    pub online_status: i32,
    pub source: Option<String>,
    pub font_size: Option<String>,
    pub main_color: Option<String>,
    pub theme: Option<String>,
    pub language: String,
    pub intro: String,
    pub template_type: i32,
    pub pdf_name: String,
}

#[derive(Insertable, Queryable, QueryableByName, Debug, Serialize, Deserialize, Default, Clone)]
#[diesel(table_name = tex_file)]
pub struct TexFile {
    pub id: i64,
    pub name: String,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub doc_status: i32,
    pub project_id: String,
    pub file_type: i32,
    pub file_id: String,
    pub parent: String,
    pub main_flag: i16,
    pub sort: i32,
    pub yjs_initial: i16,
    pub file_path: String
}

#[derive(Insertable,Queryable,QueryableByName,Debug,Serialize,Deserialize,Default,Clone)]
#[diesel(table_name = tex_proj_editor)]
pub struct TexProjEditor {
    pub id: i64,
    pub role_id: i32,
    pub created_time: i64,
    pub updated_time: i64,
    pub user_id: i64,
    pub collar_status: i32,
    pub sort: i32,
    pub project_id: String,
}