name: texhub-k8s-pro

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: ⚡ Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.ALIYUN_DOCKER_REPO_USER_NAME }}
        password: ${{ secrets.ALIYUN_DOCKER_REPO_USER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: Dockerfile-bulleye
        push: true
        tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/texhub-server:${{ github.sha }}
        # https://nova.moe/docker-attestation/
        # https://stackoverflow.com/questions/75521775/buildx-docker-image-claims-to-be-a-manifest-list
        # https://smartservice.console.aliyun.com/service/chat?spm=5176.smartservice_service_create_ticket_step_2.0.0.323d3f1bH4Z7fR&id=0005PCJF1W
        provenance: false
        sbom: false 

    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: 
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: set image --record deployment/texhub-server-service texhub-server-service=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/texhub-server:${{ github.sha }} -n reddwarf-pro

    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      timeout-minutes: 8
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0
        command: rollout status deployment/texhub-server-service -n reddwarf-pro