name: texhub-server-k8s-pro

on:
  push:
    branches: [ main ]

jobs:
  call-build:
    uses: RedDwarfTech/rd-workflow/.github/workflows/rust-app-publish-k8s.yml@main
    secrets: inherit
    with:
      target: stage
      dockerfile: Dockerfile-bulleye
      app-namespace: reddwarf-pro
      app-name: texhub-server-service
      image-name: texhub-server