name: texhub-k8s-pro

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: ⚡ Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        username: ${{ secrets.ALIYUN_DOCKER_REPO_USER_NAME }}
        password: ${{ secrets.ALIYUN_DOCKER_REPO_USER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: Dockerfile-bulleye
        push: true
        tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/texhub-server:${{ github.sha }} 

    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: 
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: set image --record deployment/texhub-server-service texhub-server-service=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/texhub-server:${{ github.sha }} -n reddwarf-pro

    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      timeout-minutes: 3
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0
        command: rollout status deployment/texhub-server-service -n reddwarf-pro